name: Build and FTP Upload

on:
  push:
    branches:
      - master 

jobs:
  ftp_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for specific project
        run: dotnet restore test/HGO.ASPNetCore.FileManager.Test/HGO.ASPNetCore.FileManager.Test.csproj

      - name: Build the specific project
        run: dotnet build test/HGO.ASPNetCore.FileManager.Test/HGO.ASPNetCore.FileManager.Test.csproj --configuration Release 

      - name: Publish the specific project
        run: dotnet publish test/HGO.ASPNetCore.FileManager.Test/HGO.ASPNetCore.FileManager.Test.csproj --configuration Release --output ./publish 

      - name: Create app_offline.htm
        run: |
          mkdir -p tmp && echo "<html><head><title>Maintenance</title><style>body{font-family:Arial,sans-serif;background-color:#f4f4f4;color:#333;text-align:center;padding:50px;}h1{color:#d9534f;}p{font-size:18px;margin-top:20px;}.container{background-color:#fff;border-radius:8px;box-shadow:0 0 10px rgba(0,0,0,0.1);padding:20px;display:inline-block;margin-top:20px;}</style></head><body><div class='container'><h1>We'll Be Right Back!</h1><p>Our application is currently undergoing scheduled maintenance.</p><p>We expect to be back in a maximum of 10 minutes.</p></div></body></html>" > tmp/app_offline.htm

      - name: Upload app_offline.htm
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./tmp/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          protocol: ftps

      - name: Wait for 5 seconds
        run: sleep 5

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          protocol: ftps
