name: Build and FTP Upload

on:
  push:
    branches:
      - master 

jobs:
  ftp_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for specific project
        run: dotnet restore test/HGO.ASPNetCore.FileManager.Test/HGO.ASPNetCore.FileManager.Test.csproj

      - name: Build the specific project
        run: dotnet build test/HGO.ASPNetCore.FileManager.Test/HGO.ASPNetCore.FileManager.Test.csproj --configuration Release 

      - name: Publish the specific project
        run: dotnet publish test/HGO.ASPNetCore.FileManager.Test/HGO.ASPNetCore.FileManager.Test.csproj --configuration Release --output ./publish 

      - name: Create app_offline.htm
        run: |
          echo "" > app_offline.htm

      - name: Upload app_offline.htm
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          protocol: ftps

      - name: Wait for 5 seconds
        run: sleep 5

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          protocol: ftps
